# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TempHumid3507.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1441, 811))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionData_Folder = QtWidgets.QAction(MainWindow)
        self.actionData_Folder.setObjectName("actionData_Folder")
        self.actionClimate_File = QtWidgets.QAction(MainWindow)
        self.actionClimate_File.setObjectName("actionClimate_File")
        self.action_Update_Climate_Data = QtWidgets.QAction(MainWindow)
        self.action_Update_Climate_Data.setObjectName("action_Update_Climate_Data")
        self.actionTemp = QtWidgets.QAction(MainWindow)
        self.actionTemp.setCheckable(True)
        self.actionTemp.setObjectName("actionTemp")
        self.actionHumid = QtWidgets.QAction(MainWindow)
        self.actionHumid.setCheckable(True)
        self.actionHumid.setObjectName("actionHumid")
        self.actionBaro = QtWidgets.QAction(MainWindow)
        self.actionBaro.setCheckable(True)
        self.actionBaro.setObjectName("actionBaro")
        self.actionGRAPH = QtWidgets.QAction(MainWindow)
        self.actionGRAPH.setObjectName("actionGRAPH")
        self.actionHDF_File = QtWidgets.QAction(MainWindow)
        self.actionHDF_File.setObjectName("actionHDF_File")
        self.toolBar.addAction(self.actionHDF_File)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionData_Folder)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGRAPH)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTemp)
        self.toolBar.addAction(self.actionHumid)
        self.toolBar.addAction(self.actionBaro)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClimate_File)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Update_Climate_Data)

        self.retranslateUi(MainWindow)
        self.actionTemp.changed.connect(self.lineEdit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Room 3507 - Environment Data"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionData_Folder.setText(_translate("MainWindow", "Data Folder"))
        self.actionClimate_File.setText(_translate("MainWindow", "Climate File"))
        self.action_Update_Climate_Data.setText(_translate("MainWindow", "!Update Climate Data!"))
        self.action_Update_Climate_Data.setToolTip(_translate("MainWindow", "Update Climate Data"))
        self.actionTemp.setText(_translate("MainWindow", "Temp"))
        self.actionHumid.setText(_translate("MainWindow", "Humid"))
        self.actionHumid.setToolTip(_translate("MainWindow", "Humid"))
        self.actionBaro.setText(_translate("MainWindow", "Baro"))
        self.actionBaro.setToolTip(_translate("MainWindow", "Baro"))
        self.actionGRAPH.setText(_translate("MainWindow", "GRAPH"))
        self.actionHDF_File.setText(_translate("MainWindow", "HDF File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
