# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TempHumid3507.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import datetime
import time
import os
import h5py
import numpy as np
import matplotlib.pyplot as plt
import glob
from dateutil.relativedelta import relativedelta
import pandas as pd
import sys
from PyQt5 import (
    QtCore, QtGui, QtWidgets
)


class Ui_MainWindow(object):
    def __init__(self):
        #declare variables for GUI
        self.datadir_path = "none selected"
        self.hdffile_path = "none selected"
        self.climatefile_path = "none selected"

        #declare variables for climatedata update
        self.inputone = None
        self.inputname = None
        self.inputconfirm = None
        self.inputbackup = None

        self.climatedataupdate = None
        self.climateupdate_size = None

        # self.savefile = None
        self.lookforfile = None

        self.length_olddata = None
        self.climatehdf5entry = None

        self.lastnum_olddata = None
        self.lastentry_olddata = None
        self.searchdata = 1
        self.updatesearch = None

        self.climate_time = None
        self.climate_time_local = None
        self.climate_temp = None
        self.climate_humid = None
        self.climate_baro = None

        self.searchrange = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1600, 800))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        #put graph 1 here
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)

        #put graph 2 here
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)


        MainWindow.setCentralWidget(self.centralwidget)
        # Setup toolbar
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        #setup toolbar actions
        self.actionData_Folder = QtWidgets.QAction(MainWindow)
        self.actionData_Folder.setObjectName("actionData_Folder")
        self.actionClimate_File = QtWidgets.QAction(MainWindow)
        self.actionClimate_File.setObjectName("actionClimate_File")
        self.action_Update_Climate_Data = QtWidgets.QAction(MainWindow)
        self.action_Update_Climate_Data.setObjectName("action_Update_Climate_Data")
        self.actionTemp = QtWidgets.QAction(MainWindow)
        self.actionTemp.setCheckable(True)
        self.actionTemp.setObjectName("actionTemp")
        self.actionHumid = QtWidgets.QAction(MainWindow)
        self.actionHumid.setCheckable(True)
        self.actionHumid.setObjectName("actionHumid")
        self.actionBaro = QtWidgets.QAction(MainWindow)
        self.actionBaro.setCheckable(True)
        self.actionBaro.setObjectName("actionBaro")
        self.actionGRAPH = QtWidgets.QAction(MainWindow)
        self.actionGRAPH.setObjectName("actionGRAPH")
        self.actionHDF_File = QtWidgets.QAction(MainWindow)
        self.actionHDF_File.setObjectName("actionHDF_File")
        self.actionDataUpdate = QtWidgets.QAction(MainWindow)
        self.actionDataUpdate.setObjectName("actionDataUpdate")

        #setup toolbar buttons
        self.toolBar.addAction(self.actionData_Folder)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHDF_File)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClimate_File)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGRAPH)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTemp)
        self.toolBar.addAction(self.actionHumid)
        self.toolBar.addAction(self.actionBaro)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Update_Climate_Data)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDataUpdate)

        # setup statusbar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        #setup connections for toolbar buttons
        self.actionData_Folder.triggered.connect(self.datafolderselect)
        self.actionHDF_File.triggered.connect(self.HDFfileselect)
        self.actionClimate_File.triggered.connect(self.climatefileselect)
        self.action_Update_Climate_Data.triggered.connect(self.initclimateupdate)
        self.actionTemp.changed.connect(self.lineEdit.clear) # type: ignore

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Room 3507 - Environment Data"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionData_Folder.setText(_translate("MainWindow", "Data Folder"))
        self.actionClimate_File.setText(_translate("MainWindow", "Climate File"))
        self.action_Update_Climate_Data.setText(_translate("MainWindow", "!Update Climate Data!"))
        self.action_Update_Climate_Data.setToolTip(_translate("MainWindow", "Update Climate Data"))
        self.actionTemp.setText(_translate("MainWindow", "Temp"))
        self.actionHumid.setText(_translate("MainWindow", "Humid"))
        self.actionHumid.setToolTip(_translate("MainWindow", "Humid"))
        self.actionBaro.setText(_translate("MainWindow", "Baro"))
        self.actionBaro.setToolTip(_translate("MainWindow", "Baro"))
        self.actionGRAPH.setText(_translate("MainWindow", "GRAPH"))
        self.actionHDF_File.setText(_translate("MainWindow", "HDF File"))
        self.actionDataUpdate.setText(_translate("MainWindow", "!Update Data!"))


    def datafolderselect(self):
        print("click data folder")
        print(self.datadir_path)
        self.datadir_path = QtWidgets.QFileDialog.getExistingDirectory()
        self.actionData_Folder.setStatusTip(self.datadir_path)
        print(self.datadir_path)
        # self.fileboxlist()

    def HDFfileselect(self):
        print("click hdf file")
        print(self.hdffile_path)
        self.hdffile_path, _ = QtWidgets.QFileDialog.getSaveFileName()
        print(self.hdffile_path)
        # self.fileboxlist()

    def climatefileselect(self):
        print("click climate file")
        print(self.climatefile_path)
        self.climatefile_path, _ = QtWidgets.QFileDialog.getOpenFileName()
        print(self.climatefile_path)

        # self.fileboxlist()

    def initclimateupdate(self):

        #take CVS update file and put in Pandas array - determine size
        print("opening weather file")
        self.climatedataupdate = pd.read_csv(self.climatefile_path, index_col='date_time_local')
        self.climateupdate_size = self.climatedataupdate.shape[0]

        # checks to see if the file already exist - if the file does not exist make it and put data in.
        #self.savefile = self.filenameloc + self.h5pyclimate
        #self.lookforfile = os.path.isfile(self.savefile)
        #print('Is HD5F file present?')
        #print(self.lookforfile)
        #self.savefile = self.hdffile_path
        self.climatehdf5size()

    def climatehdf5size(self):
        print("check hdf file path")
        if os.path.isfile(self.hdffile_path):
            print('Opening HDF5 file')
            with h5py.File(self.hdffile_path, 'a') as f:
                self.length_olddata = len(f['compiled_data'])
                print('size of the climate HD5F array')
                print(self.length_olddata)
                print('closing file after size check')
                f.close()
        else:
            print('making HDF5 file')
            # if the file does not exist - create it and set up
            with h5py.File(self.hdffile_path, 'a') as f:
                data_type = np.dtype('float')
                self.climatehdf5entry = f.create_dataset('compiled_data', shape=(1, 8), maxshape=(None, 8), dtype=data_type)
                self.length_olddata = len(f['compiled_data'])
                print('size of the climate HD5F array')
                print(self.length_olddata)
                print('closing file after create')
                f.close()
        self.climateupdatesearch()

    def climateupdatesearch(self):
        if os.path.isfile(self.hdffile_path):
            print('Opening HDF5 file')
            self.lastnum_olddata = self.length_olddata - 1
            with h5py.File(self.hdffile_path, 'a') as f:
                self.lastentry_olddata = f['compiled_data'][self.lastnum_olddata, 0]
                f.close()
            # scan the unix time to see if new number is there
            while self.searchdata == 1:
                self.climateupdate_size = self.climateupdate_size - 1
                if self.climateupdate_size < 0:
                    self.searchdata = 2
                    print('the update file does not go back far enough for consistent data, re-download with more rows')
                    print('if this is a new file then continue')
                    self.inputconfirm = input('Do you want to continue? (y or n)')
                    if self.inputconfirm == 'y':
                        self.climateupdate_size = self.climatedataupdate.shape[0] - 1
                        print('size to use is:')
                        print(self.climateupdate_size)
                    else:
                        return()
                self.updatesearch = self.climatedataupdate.unixtime[self.climateupdate_size]
                if self.updatesearch == self.lastentry_olddata:
                    self.searchdata = 2
                    print('Starting entry ')
                    print(self.climateupdate_size)
                    self.climateupdate_size = self.climateupdate_size - 1
                    with h5py.File(self.hdffile_path, 'a') as f:
                        self.lastnum_olddata = len(f['compiled_data'])
                        f['compiled_data'].resize((f['compiled_data'].shape[0] + 1, f['compiled_data'].shape[1]))
                        f.close()
                    print('entry location')
                    print(self.lastnum_olddata)
        self.climateupdatecompile()

    def climateupdatecompile(self):
        if os.path.isfile(self.hdffile_path):
            print('Opening HDF5 file')
            with h5py.File(self.hdffile_path, 'a') as f:
                self.lastnum_olddata = len(f['compiled_data']) - 1
                print('using location in existing')
                print(self.lastnum_olddata)
                self.searchrange = self.climateupdate_size + 1
                for passnum in range(self.searchrange):
                    print('defined range:')
                    print(self.searchrange)
                    print('search range passnum:')
                    print(passnum)
                    if self.climateupdate_size < 0:
                        print('complete')
                    else:
                        print('location within update array')
                        print(self.climateupdate_size)
                        self.climate_time = self.climatedataupdate.unixtime[self.climateupdate_size]
                        self.climate_temp = self.climatedataupdate.temperature[self.climateupdate_size]
                        self.climate_humid = self.climatedataupdate.relative_humidity[self.climateupdate_size]
                        self.climate_baro = self.climatedataupdate.pressure_station[self.climateupdate_size]
                        self.climateupdate_size -= 1
                        f['compiled_data'][self.lastnum_olddata, 0] = self.climate_time
                        f['compiled_data'][self.lastnum_olddata, 1] = self.climate_temp
                        f['compiled_data'][self.lastnum_olddata, 2] = self.climate_humid
                        f['compiled_data'][self.lastnum_olddata, 3] = self.climate_baro
                        print('entering climate data location lastnum_olddata')
                        print(self.lastnum_olddata)
                        self.lastnum_olddata += 1
                        if passnum < self.searchrange - 1:
                            f['compiled_data'].resize((f['compiled_data'].shape[0] + 1, f['compiled_data'].shape[1]))
                f.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
